Found 5 items
-rw-r--r--   3 root supergroup 1073741824 2019-03-25 14:54 /myfile1
-rw-r--r--   3 root supergroup 1073741824 2019-03-25 14:55 /myfile2._COPYING_
-rw-r--r--   3 root supergroup 1073741824 2019-03-25 14:54 /myfile3
-rw-r--r--   3 root supergroup  939524096 2019-03-25 14:54 /myfile4._COPYING_
-rw-r--r--   3 root supergroup 1073741824 2019-03-25 14:54 /myfile5
file 3 has been put into HDFS
file 3 has been read from HDFS for 1 time
diff succeed!
file 3 has been read from HDFS for 2 time
diff succeed!
file 3 has been read from HDFS for 3 time
diff succeed!
file 3 has been read from HDFS for 4 time
diff succeed!
file 3 has been read from HDFS for 5 time
diff succeed!
file 3 has been read from HDFS for 6 time
diff succeed!
file 3 has been read from HDFS for 7 time
diff succeed!
file 3 has been read from HDFS for 8 time
diff succeed!
file 3 has been read from HDFS for 9 time
diff succeed!
file 3 has been read from HDFS for 10 time
diff succeed!
Deleted /myfile3
file 3 has been removed from HDFS
Found 3 items
-rw-r--r--   3 root supergroup 1073741824 2019-03-25 14:56 /myfile1
-rw-r--r--   3 root supergroup 1073741824 2019-03-25 14:56 /myfile2
-rw-r--r--   3 root supergroup 1073741824 2019-03-25 14:56 /myfile3
file 3 has been put into HDFS
file 3 has been read from HDFS for 1 time
diff succeed!
file 3 has been read from HDFS for 2 time
diff succeed!
file 3 has been read from HDFS for 3 time
diff succeed!
file 3 has been read from HDFS for 4 time
diff succeed!
file 3 has been read from HDFS for 5 time
diff succeed!
file 3 has been read from HDFS for 6 time
diff succeed!
file 3 has been read from HDFS for 7 time
diff succeed!
file 3 has been read from HDFS for 8 time
diff succeed!
file 3 has been read from HDFS for 9 time
diff succeed!
file 3 has been read from HDFS for 10 time
diff succeed!
Deleted /myfile3
file 3 has been removed from HDFS
Found 4 items
-rw-r--r--   3 root supergroup 1073741824 2019-03-25 14:58 /myfile1
-rw-r--r--   3 root supergroup  939524096 2019-03-25 14:58 /myfile2._COPYING_
-rw-r--r--   3 root supergroup 1073741824 2019-03-25 14:58 /myfile3
-rw-r--r--   3 root supergroup 1073741824 2019-03-25 14:57 /myfile5
file 3 has been put into HDFS
file 3 has been read from HDFS for 1 time
diff succeed!
file 3 has been read from HDFS for 2 time
diff succeed!
file 3 has been read from HDFS for 3 time
diff succeed!
file 3 has been read from HDFS for 4 time
diff succeed!
file 3 has been read from HDFS for 5 time
diff succeed!
file 3 has been read from HDFS for 6 time
diff succeed!
file 3 has been read from HDFS for 7 time
diff succeed!
file 3 has been read from HDFS for 8 time
diff succeed!
file 3 has been read from HDFS for 9 time
diff succeed!
file 3 has been read from HDFS for 10 time
diff succeed!
Deleted /myfile3
file 3 has been removed from HDFS
Found 5 items
-rw-r--r--   3 root supergroup 1073741824 2019-03-25 14:59 /myfile1
-rw-r--r--   3 root supergroup 1073741824 2019-03-25 15:00 /myfile2
-rw-r--r--   3 root supergroup 1073741824 2019-03-25 15:00 /myfile3
-rw-r--r--   3 root supergroup 1073741824 2019-03-25 14:58 /myfile4
-rw-r--r--   3 root supergroup 1073741824 2019-03-25 14:59 /myfile5
file 3 has been put into HDFS
file 3 has been read from HDFS for 1 time
diff succeed!
file 3 has been read from HDFS for 2 time
diff succeed!
file 3 has been read from HDFS for 3 time
diff succeed!
file 3 has been read from HDFS for 4 time
diff succeed!
file 3 has been read from HDFS for 5 time
diff succeed!
file 3 has been read from HDFS for 6 time
diff succeed!
file 3 has been read from HDFS for 7 time
diff succeed!
file 3 has been read from HDFS for 8 time
diff succeed!
file 3 has been read from HDFS for 9 time
diff succeed!
file 3 has been read from HDFS for 10 time
diff succeed!
Deleted /myfile3
file 3 has been removed from HDFS
Found 5 items
-rw-r--r--   3 root supergroup 1073741824 2019-03-25 15:01 /myfile1
-rw-r--r--   3 root supergroup 1073741824 2019-03-25 15:02 /myfile2
-rw-r--r--   3 root supergroup 1073741824 2019-03-25 15:02 /myfile3
-rw-r--r--   3 root supergroup 1073741824 2019-03-25 15:01 /myfile4
-rw-r--r--   3 root supergroup 1073741824 2019-03-25 15:01 /myfile5
file 3 has been put into HDFS
file 3 has been read from HDFS for 1 time
diff succeed!
file 3 has been read from HDFS for 2 time
diff succeed!
file 3 has been read from HDFS for 3 time
diff succeed!
file 3 has been read from HDFS for 4 time
diff succeed!
file 3 has been read from HDFS for 5 time
diff succeed!
file 3 has been read from HDFS for 6 time
diff succeed!
file 3 has been read from HDFS for 7 time
diff succeed!
file 3 has been read from HDFS for 8 time
diff succeed!
file 3 has been read from HDFS for 9 time
diff succeed!
file 3 has been read from HDFS for 10 time
diff succeed!
Deleted /myfile3
file 3 has been removed from HDFS
Found 5 items
-rw-r--r--   3 root supergroup 1073741824 2019-03-25 15:03 /myfile1
-rw-r--r--   3 root supergroup 1073741824 2019-03-25 15:04 /myfile2
-rw-r--r--   3 root supergroup 1073741824 2019-03-25 15:04 /myfile3
-rw-r--r--   3 root supergroup 1073741824 2019-03-25 15:03 /myfile4
-rw-r--r--   3 root supergroup 1073741824 2019-03-25 15:03 /myfile5
file 3 has been put into HDFS
file 3 has been read from HDFS for 1 time
diff succeed!
file 3 has been read from HDFS for 2 time
diff succeed!
file 3 has been read from HDFS for 3 time
diff succeed!
file 3 has been read from HDFS for 4 time
diff succeed!
file 3 has been read from HDFS for 5 time
diff succeed!
file 3 has been read from HDFS for 6 time
diff succeed!
2019-03-25 15:05:32,737 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - java.net.ConnectException: Call From clnode051.clemson.cloudlab.us/130.127.133.60 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 895ms.
2019-03-25 15:05:33,639 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.ipc.StandbyException): Operation category READ is not supported in state standby. Visit https://s.apache.org/sbnn-error
	at org.apache.hadoop.hdfs.server.namenode.ha.StandbyState.checkOperation(StandbyState.java:88)
	at org.apache.hadoop.hdfs.server.namenode.NameNode$NameNodeHAContext.checkOperation(NameNode.java:1952)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkOperation(FSNamesystem.java:1423)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getFileInfo(FSNamesystem.java:3085)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getFileInfo(NameNodeRpcServer.java:1154)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getFileInfo(ClientNamenodeProtocolServerSideTranslatorPB.java:966)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:523)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:991)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:872)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:818)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1729)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2678)
, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1757ms.
2019-03-25 15:05:35,399 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - java.net.ConnectException: Call From clnode051.clemson.cloudlab.us/130.127.133.60 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 3810ms.
file 3 has been read from HDFS for 7 time
diff succeed!
file 3 has been read from HDFS for 8 time
diff succeed!
file 3 has been read from HDFS for 9 time
diff succeed!
2019-03-25 15:06:29,631 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - java.io.EOFException: End of File Exception between local host is: "clnode051.clemson.cloudlab.us/130.127.133.60"; destination host is: "node-1-link-0":8020; : java.io.EOFException; For more details see:  http://wiki.apache.org/hadoop/EOFException, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 625ms.
2019-03-25 15:06:30,263 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - java.net.ConnectException: Call From clnode051.clemson.cloudlab.us/130.127.133.60 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2230ms.
2019-03-25 15:06:32,495 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - java.net.ConnectException: Call From clnode051.clemson.cloudlab.us/130.127.133.60 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 2398ms.
2019-03-25 15:06:34,899 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - java.net.ConnectException: Call From clnode051.clemson.cloudlab.us/130.127.133.60 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 7417ms.
2019-03-25 15:06:42,318 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - java.net.ConnectException: Call From clnode051.clemson.cloudlab.us/130.127.133.60 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 21035ms.
2019-03-25 15:07:03,356 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - java.net.ConnectException: Call From clnode051.clemson.cloudlab.us/130.127.133.60 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 14667ms.
2019-03-25 15:07:18,025 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - java.net.ConnectException: Call From clnode051.clemson.cloudlab.us/130.127.133.60 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 18078ms.
2019-03-25 15:07:36,105 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - java.net.ConnectException: Call From clnode051.clemson.cloudlab.us/130.127.133.60 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 18432ms.
